name: hackathon_env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pandas
  - numpy
  - scikit-learn
  - scipy
  - plotly
  - matplotlib
  - seaborn
  - jupyter
  - ipykernel
  - pytest
  - xgboost
  - imbalanced-learn
  - scikit-image
  - openpyxl
  - pyarrow
  - pymongo
  - statsmodels
  - requests
  - beautifulsoup4
  - pillow
  - imageio